import { CandidateMove } from './candidate-move.model';
import { ChatMessage } from './chat-message.model';
import { DurationOption } from './duration-option.model';
import { Hand } from './hand.model';
import { Lane } from './lane.model';
import { MoveMade } from './move-made.model';
import { PlayerOrNone } from './player-or-none.model';

export type PlayerGameView = {
  hand: Hand;
  lanes: Lane[];
  numCardsInOpponentsDeck: number;
  numCardsInOpponentsHand: number;
  numCardsInPlayersDeck: number;
  isHost: boolean;
  isHostPlayersTurn: boolean;
  redJokerLaneIndex?: number;
  blackJokerLaneIndex?: number;
  gameCreatedTimestampUTC: string;
  movesMade: MoveMade[];
  durationOption: DurationOption;
  gameEndedTimestampUTC?: string;
  gameCode: string;
  candidateMoves?: CandidateMove[];
  hasEnded: boolean;
  chatMessages: ChatMessage[];
  hostName?: string;
  guestName?: string;
  hostSecondsRemaining: number;
  guestSecondsRemaining: number;
  wonBy: PlayerOrNone;
  numUnreadMessages: number;
};
