export enum Z_INDEXES {
  POSITION_MARKER_CONTAINER = 10,
  POSITION_CONTENT = 20,
  PLACE_MULTIPLE_CARDS_OVERLAY = 30,
  PLACE_MULTIPLE_CARDS_LANE_BACKGROUND = 40,
  PLACE_MULTIPLE_CARDS = 50,
  ANIMATION_OVERLAY = 60,
}
